<?php

namespace Container5TQ2QDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RbR9ZvWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RbR9ZvW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RbR9ZvW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evRepository' => ['privates', 'App\\Repository\\EvRepository', 'getEvRepositoryService', true],
            'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService', true],
        ], [
            'evRepository' => 'App\\Repository\\EvRepository',
            'settingRepository' => 'App\\Repository\\SettingRepository',
        ]);
    }
}
