<?php

namespace Container6pbkfm7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xn87EYVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xn87EYV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xn87EYV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ev' => ['privates', '.errored..service_locator.xn87EYV.App\\Entity\\Ev', NULL, 'Cannot autowire service ".service_locator.xn87EYV": it references class "App\\Entity\\Ev" but no such service exists.'],
            'imageRepository' => ['privates', '.errored.SaDKNAR', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::show()": the $imageRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\Admin\\ImageRepository".'],
        ], [
            'ev' => 'App\\Entity\\Ev',
            'imageRepository' => '?',
        ]);
    }
}
