<?php

namespace Container6pbkfm7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O9dvn8eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O9dvn8e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O9dvn8e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messagesRepository' => ['privates', 'App\\Repository\\Admin\\MessagesRepository', 'getMessagesRepositoryService', true],
        ], [
            'messagesRepository' => 'App\\Repository\\Admin\\MessagesRepository',
        ]);
    }
}
