<?php

namespace Container3w6vYsr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SnQWg6vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.snQWg6v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.snQWg6v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\CategoryController::delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\CategoryController::edit' => ['privates', '.service_locator.vG92.Jb', 'get_ServiceLocator_VG92_JbService', true],
            'App\\Controller\\Admin\\CategoryController::index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController::new' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController::show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\EvController::delete' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController::edit' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController::index' => ['privates', '.service_locator.HOg8xP7', 'get_ServiceLocator_HOg8xP7Service', true],
            'App\\Controller\\Admin\\EvController::show' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\ImageController::delete' => ['privates', '.service_locator.99JoYyf', 'get_ServiceLocator_99JoYyfService', true],
            'App\\Controller\\Admin\\ImageController::edit' => ['privates', '.service_locator.OxooMSx', 'get_ServiceLocator_OxooMSxService', true],
            'App\\Controller\\Admin\\ImageController::index' => ['privates', '.service_locator.cnYEmTx', 'get_ServiceLocator_CnYEmTxService', true],
            'App\\Controller\\Admin\\ImageController::new' => ['privates', '.service_locator.cnYEmTx', 'get_ServiceLocator_CnYEmTxService', true],
            'App\\Controller\\Admin\\ImageController::show' => ['privates', '.service_locator.gA6au_5', 'get_ServiceLocator_GA6au5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\CategoryController:delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\CategoryController:edit' => ['privates', '.service_locator.vG92.Jb', 'get_ServiceLocator_VG92_JbService', true],
            'App\\Controller\\Admin\\CategoryController:index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController:new' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController:show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\EvController:delete' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController:edit' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController:index' => ['privates', '.service_locator.HOg8xP7', 'get_ServiceLocator_HOg8xP7Service', true],
            'App\\Controller\\Admin\\EvController:show' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\ImageController:delete' => ['privates', '.service_locator.99JoYyf', 'get_ServiceLocator_99JoYyfService', true],
            'App\\Controller\\Admin\\ImageController:edit' => ['privates', '.service_locator.OxooMSx', 'get_ServiceLocator_OxooMSxService', true],
            'App\\Controller\\Admin\\ImageController:index' => ['privates', '.service_locator.cnYEmTx', 'get_ServiceLocator_CnYEmTxService', true],
            'App\\Controller\\Admin\\ImageController:new' => ['privates', '.service_locator.cnYEmTx', 'get_ServiceLocator_CnYEmTxService', true],
            'App\\Controller\\Admin\\ImageController:show' => ['privates', '.service_locator.gA6au_5', 'get_ServiceLocator_GA6au5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\CategoryController::delete' => '?',
            'App\\Controller\\Admin\\CategoryController::edit' => '?',
            'App\\Controller\\Admin\\CategoryController::index' => '?',
            'App\\Controller\\Admin\\CategoryController::new' => '?',
            'App\\Controller\\Admin\\CategoryController::show' => '?',
            'App\\Controller\\Admin\\EvController::delete' => '?',
            'App\\Controller\\Admin\\EvController::edit' => '?',
            'App\\Controller\\Admin\\EvController::index' => '?',
            'App\\Controller\\Admin\\EvController::show' => '?',
            'App\\Controller\\Admin\\ImageController::delete' => '?',
            'App\\Controller\\Admin\\ImageController::edit' => '?',
            'App\\Controller\\Admin\\ImageController::index' => '?',
            'App\\Controller\\Admin\\ImageController::new' => '?',
            'App\\Controller\\Admin\\ImageController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\CategoryController:delete' => '?',
            'App\\Controller\\Admin\\CategoryController:edit' => '?',
            'App\\Controller\\Admin\\CategoryController:index' => '?',
            'App\\Controller\\Admin\\CategoryController:new' => '?',
            'App\\Controller\\Admin\\CategoryController:show' => '?',
            'App\\Controller\\Admin\\EvController:delete' => '?',
            'App\\Controller\\Admin\\EvController:edit' => '?',
            'App\\Controller\\Admin\\EvController:index' => '?',
            'App\\Controller\\Admin\\EvController:show' => '?',
            'App\\Controller\\Admin\\ImageController:delete' => '?',
            'App\\Controller\\Admin\\ImageController:edit' => '?',
            'App\\Controller\\Admin\\ImageController:index' => '?',
            'App\\Controller\\Admin\\ImageController:new' => '?',
            'App\\Controller\\Admin\\ImageController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
