<?php

namespace Container3w6vYsr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_SczYhjbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.SczYhjb' shared service.
     *
     * @return \App\Entity\Admin\Image
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Admin\\ImageController::delete()": the $image argument is type-hinted with the non-existent class or interface: "App\\Entity\\Admin\\Image".');
    }
}
