<?php

namespace ContainerT7Q4eEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEv3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qNn3kGW.App\Entity\Ev' shared service.
     *
     * @return \App\Entity\Ev
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qNn3kGW": it references class "App\\Entity\\Ev" but no such service exists.');
    }
}
