<?php

namespace ContainerT7Q4eEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Admin\ReservationType' shared autowired service.
     *
     * @return \App\Form\Admin\ReservationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\Admin\\ReservationType.php';

        return $container->privates['App\\Form\\Admin\\ReservationType'] = new \App\Form\Admin\ReservationType();
    }
}
