<?php

namespace ContainerKSt484r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ImageType' shared autowired service.
     *
     * @return \App\Form\ImageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\ImageType.php';

        return $container->privates['App\\Form\\ImageType'] = new \App\Form\ImageType();
    }
}
