<?php

namespace ContainerYDCxbLX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FsreGkyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fsreGky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fsreGky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'reservationRepository' => ['privates', '.errored.iNgrhO3', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::reservations()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ReservationRepository". Did you forget to add a use statement?'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'reservationRepository' => '?',
        ]);
    }
}
