<?php

namespace ContainerYDCxbLX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_INgrhO3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.iNgrhO3' shared service.
     *
     * @return \App\Controller\ReservationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::reservations()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ReservationRepository". Did you forget to add a use statement?');
    }
}
