<?php

namespace ContainerTDm3X92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xd830CVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xd830CV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xd830CV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'ev' => ['privates', '.errored..service_locator.Xd830CV.App\\Entity\\Ev', NULL, 'Cannot autowire service ".service_locator.Xd830CV": it references class "App\\Entity\\Ev" but no such service exists.'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'ev' => 'App\\Entity\\Ev',
        ]);
    }
}
