<?php

namespace ContainerXLGjW2g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sk9zFNwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sk9zFNw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sk9zFNw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evRepository' => ['privates', '.errored.A98xaeS', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::newreservation()": the $evRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvRepository". Did you forget to add a use statement?'],
        ], [
            'evRepository' => '?',
        ]);
    }
}
