<?php

namespace ContainerXLGjW2g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_A98xaeSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.A98xaeS' shared service.
     *
     * @return \App\Controller\EvRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::newreservation()": the $evRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvRepository". Did you forget to add a use statement?');
    }
}
