<?php

namespace ContainerXLGjW2g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vcKDXoT.App\Entity\Admin\Homes' shared service.
     *
     * @return \App\Entity\Admin\Homes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vcKDXoT": it references class "App\\Entity\\Admin\\Homes" but no such service exists.');
    }
}
