<?php

namespace ContainerJM2oXfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z98ZIg7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z98ZIg7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z98ZIg7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\CategoryController::delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\CategoryController::edit' => ['privates', '.service_locator.vG92.Jb', 'get_ServiceLocator_VG92_JbService', true],
            'App\\Controller\\Admin\\CategoryController::index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController::new' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController::show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\EvController::delete' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController::edit' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController::index' => ['privates', '.service_locator.HOg8xP7', 'get_ServiceLocator_HOg8xP7Service', true],
            'App\\Controller\\Admin\\EvController::show' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\CategoryController:delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\CategoryController:edit' => ['privates', '.service_locator.vG92.Jb', 'get_ServiceLocator_VG92_JbService', true],
            'App\\Controller\\Admin\\CategoryController:index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController:new' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\Admin\\CategoryController:show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\Admin\\EvController:delete' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController:edit' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'App\\Controller\\Admin\\EvController:index' => ['privates', '.service_locator.HOg8xP7', 'get_ServiceLocator_HOg8xP7Service', true],
            'App\\Controller\\Admin\\EvController:show' => ['privates', '.service_locator.qNn3kGW', 'get_ServiceLocator_QNn3kGWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\CategoryController::delete' => '?',
            'App\\Controller\\Admin\\CategoryController::edit' => '?',
            'App\\Controller\\Admin\\CategoryController::index' => '?',
            'App\\Controller\\Admin\\CategoryController::new' => '?',
            'App\\Controller\\Admin\\CategoryController::show' => '?',
            'App\\Controller\\Admin\\EvController::delete' => '?',
            'App\\Controller\\Admin\\EvController::edit' => '?',
            'App\\Controller\\Admin\\EvController::index' => '?',
            'App\\Controller\\Admin\\EvController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\CategoryController:delete' => '?',
            'App\\Controller\\Admin\\CategoryController:edit' => '?',
            'App\\Controller\\Admin\\CategoryController:index' => '?',
            'App\\Controller\\Admin\\CategoryController:new' => '?',
            'App\\Controller\\Admin\\CategoryController:show' => '?',
            'App\\Controller\\Admin\\EvController:delete' => '?',
            'App\\Controller\\Admin\\EvController:edit' => '?',
            'App\\Controller\\Admin\\EvController:index' => '?',
            'App\\Controller\\Admin\\EvController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
