<?php

namespace ContainerQ3OGWQg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CbPKdFIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CbPKdFI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CbPKdFI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ev' => ['privates', '.errored..service_locator.CbPKdFI.App\\Entity\\Ev', NULL, 'Cannot autowire service ".service_locator.CbPKdFI": it references class "App\\Entity\\Ev" but no such service exists.'],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'ev' => 'App\\Entity\\Ev',
            'imageRepository' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
