<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJmeYui\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJmeYui/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHJmeYui.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHJmeYui\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHJmeYui\App_KernelDevDebugContainer([
    'container.build_hash' => 'HJmeYui',
    'container.build_id' => 'fa0b6a0f',
    'container.build_time' => 1597247321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJmeYui');
