<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8LUf5g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8LUf5g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8LUf5g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8LUf5g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX8LUf5g\App_KernelDevDebugContainer([
    'container.build_hash' => 'X8LUf5g',
    'container.build_id' => '26decfaa',
    'container.build_time' => 1597278296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8LUf5g');
