<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxuDarx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxuDarx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxuDarx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxuDarx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxuDarx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxuDarx',
    'container.build_id' => '1d534b3e',
    'container.build_time' => 1597197056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxuDarx');
