<?php

namespace Container8jYVGMg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Admin\CommentType' shared autowired service.
     *
     * @return \App\Form\Admin\CommentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\Admin\\CommentType.php';

        return $container->privates['App\\Form\\Admin\\CommentType'] = new \App\Form\Admin\CommentType();
    }
}
