<?php

namespace Container8jYVGMg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEv2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v7vxJV1.App\Entity\Ev' shared service.
     *
     * @return \App\Entity\Ev
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.v7vxJV1": it references class "App\\Entity\\Ev" but no such service exists.');
    }
}
