<?php

namespace ContainerMIFC0jt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__WwnQdyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..WwnQdy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..WwnQdy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'user' => ['privates', '.errored..service_locator..WwnQdy.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator..WwnQdy": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
