<?php

namespace ContainerMIFC0jt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__VG4VJXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..vG4VJX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..vG4VJX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'evRepository' => ['privates', 'App\\Repository\\EvRepository', 'getEvRepositoryService', true],
            'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'evRepository' => 'App\\Repository\\EvRepository',
            'settingRepository' => 'App\\Repository\\SettingRepository',
        ]);
    }
}
