<?php

namespace ContainerMIFC0jt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XFfswMO.App\Entity\Image' shared service.
     *
     * @return \App\Entity\Image
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XFfswMO": it references class "App\\Entity\\Image" but no such service exists.');
    }
}
